// src/components/ui/Header.tsx
'use client';

import { MyLink } from './MyLink';
import { ThemeToggle } from './ThemeToggle';
import { MobileMenu } from './MobileMenu';
import { motion } from 'framer-motion';
import { Code2 } from 'lucide-react';
import { usePathname } from 'next/navigation';
import { cn } from '@/lib/utils';

export function Header() {
    const pathname = usePathname();

    const navItems = [
        { href: '/', label: 'Home' },
        { href: '/about', label: 'About' },
        { href: '/blog', label: 'Blog' },
    ];

    return (
        <motion.header
            className="sticky top-0 z-50 bg-background/80 backdrop-blur-sm border-b border-border/40"
            initial={{ y: -20, opacity: 0 }}
            animate={{ y: 0, opacity: 1 }}
            transition={{ duration: 0.3 }}
        >
            <div className="container mx-auto px-6 py-3">
                <nav className="flex justify-between items-center max-w-7xl mx-auto">
                    <MyLink href="/" className="text-lg font-bold flex items-center gap-2 group">
                        <Code2 className="w-5 h-5 text-primary" />
                        <span>Ricardo</span>
                    </MyLink>
                    <div className="flex items-center gap-6">
                        {/* Desktop Navigation */}
                        <ul className="hidden lg:flex gap-8">
                            {navItems.map((item) => (
                                <li key={item.href}>
                                    <MyLink
                                        href={item.href}
                                        variant="nav"
                                        className={cn(
                                            "text-sm font-medium transition-colors",
                                            pathname === item.href ? "text-foreground" : "text-muted-foreground hover:text-foreground"
                                        )}
                                    >
                                        {item.label}
                                    </MyLink>
                                </li>
                            ))}
                        </ul>

                        {/* Theme Toggle */}
                        <ThemeToggle />

                        {/* Mobile Menu */}
                        <MobileMenu items={navItems} />
                    </div>
                </nav>
            </div>
        </motion.header>
    );
}

// components/Header.vue
<script setup lang="ts">
import MyText from './Atons/MyText';
import ToggleMode from './Atons/ToggleMode.vue';

const toggleTheme = () => {
  const html = document.querySelector('html');
  html!.classList.toggle('dark');
  localStorage.setItem(
    'theme',
    html!.classList.contains('dark') ? 'dark' : 'light'
  );
};

const NAV_MENU = [
  {
    name: 'Projects',
    href: '#',
  },
  {
    name: 'Tech',
    href: '#',
  },
  {
    name: 'About Me',
    href: '#',
  },
  {
    name: 'Contact Me',
    href: '#',
  },
  {
    name: 'Blog',
    href: '/blog',
  },
];
</script>

<template>
  <header class="bg-background p-5">
    <div class="container flex justify-between h-14 items-center">
      <MyText variant="h4">
        <NuxtLink to="/"> Ricardo Dev. </NuxtLink>
      </MyText>
      <div class="mr-4 hidden md:flex">
        <nav class="flex items-center space-x-6 text-sm font-medium">
          <NuxtLink
            v-for="item in NAV_MENU"
            :key="item.name"
            :href="item.href"
            class="text-primary text-xl link-animation relative"
            >{{ item.name }}</NuxtLink
          >
        </nav>
      </div>
      <div @click="toggleTheme" class="flex items-center gap-x-1">
        <ToggleMode />
      </div>
    </div>
  </header>
</template>

<style scoped>
.link-animation::before {
  content: '';
  position: absolute;
  bottom: -0.3rem;
  left: 50%;
  width: 0;
  height: 2px;
  background-color: hsl(var(--primary));
  transition: width 0.3s ease-out, left 0.3s ease-out;
}

.link-animation:hover:before {
  width: 100%;
  left: 0;
}
</style>
